# Generated by Django 2.2.4 on 2019-08-03 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Write time')),
                ('read_count', models.IntegerField(default=0)),
                ('author', models.CharField(max_length=100)),
                ('context', models.CharField(max_length=1000)),
                ('logo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('src', models.CharField(max_length=200)),
                ('date', models.DateField(verbose_name='Write time')),
                ('read_count', models.IntegerField(default=0)),
                ('author', models.CharField(max_length=100)),
                ('context', models.CharField(max_length=1000)),
                ('type_num', models.IntegerField(default=0)),
                ('effect', models.CharField(max_length=100)),
                ('type_text', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
