# Generated by Django 2.2.4 on 2019-08-06 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20190803_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tt', models.CharField(max_length=100)),
                ('date', models.DateField(verbose_name='Write time')),
                ('read_count', models.IntegerField(default=0)),
                ('author', models.CharField(max_length=100)),
                ('context', models.CharField(max_length=1000)),
                ('logo', models.CharField(max_length=200)),
                ('news_type', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
