# Generated by Django 2.2.4 on 2019-08-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20190806_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_solu',
            field=models.IntegerField(default=0),
        ),
    ]
