# Generated by Django 2.2.4 on 2019-08-07 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_products_is_solu'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='classify',
            field=models.IntegerField(default=0),
        ),
    ]
