# Generated by Django 2.2.4 on 2019-08-07 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_products_classify'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=11)),
            ],
        ),
    ]
