# Generated by Django 2.2.4 on 2019-08-10 03:09

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_joinus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mynews',
            name='context',
            field=DjangoUeditor.models.UEditorField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='products',
            name='context',
            field=DjangoUeditor.models.UEditorField(verbose_name='内容'),
        ),
    ]
