# Generated by Django 2.2.4 on 2019-08-10 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20190810_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mynews',
            name='logo',
            field=models.FileField(upload_to='./static/uploadfile/', verbose_name='新闻图片'),
        ),
        migrations.AlterField(
            model_name='products',
            name='src',
            field=models.FileField(upload_to='./static/uploadfile/', verbose_name='产品图片'),
        ),
    ]
