# Generated by Django 2.2.4 on 2019-08-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20190810_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mynews',
            name='logo',
            field=models.ImageField(default='', upload_to='org/%Y/%m', verbose_name='新闻图片'),
        ),
        migrations.AlterField(
            model_name='products',
            name='src',
            field=models.ImageField(default='', upload_to='org/%Y/%m', verbose_name='产品图片'),
        ),
    ]
