# Generated by Django 2.2.4 on 2019-08-12 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20190810_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(default='', upload_to='banner/%Y/%m', verbose_name='轮播图片')),
            ],
        ),
    ]
