# Generated by Django 2.2.4 on 2019-08-13 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_banner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mynews',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='banner',
            name='url',
            field=models.ImageField(default='', upload_to='banner/%Y/%m', verbose_name='分辨率1920X758,非白底图片更优'),
        ),
        migrations.AlterField(
            model_name='joinus',
            name='Product',
            field=models.CharField(max_length=100, verbose_name='产品名称'),
        ),
        migrations.AlterField(
            model_name='joinus',
            name='area',
            field=models.CharField(max_length=100, verbose_name='地区'),
        ),
        migrations.AlterField(
            model_name='joinus',
            name='name',
            field=models.CharField(max_length=100, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='joinus',
            name='tel',
            field=models.CharField(max_length=11, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='mynews',
            name='author',
            field=models.CharField(max_length=100, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='mynews',
            name='date',
            field=models.DateField(verbose_name='编写日期'),
        ),
        migrations.AlterField(
            model_name='mynews',
            name='news_type',
            field=models.IntegerField(default=0, verbose_name='新闻类别'),
        ),
        migrations.AlterField(
            model_name='mynews',
            name='read_count',
            field=models.IntegerField(default=0, verbose_name='阅读量'),
        ),
        migrations.AlterField(
            model_name='mynews',
            name='tt',
            field=models.CharField(max_length=100, verbose_name='新闻标题'),
        ),
        migrations.AlterField(
            model_name='products',
            name='author',
            field=models.CharField(max_length=100, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='products',
            name='classify',
            field=models.IntegerField(default=0, verbose_name='解决方案的分类号 0:无效,1:SCR系统解决方案 ,2:燃油系统解决方案,3:润滑系统决方案,4:EGR系统解决方案'),
        ),
        migrations.AlterField(
            model_name='products',
            name='date',
            field=models.DateField(verbose_name='编写日期'),
        ),
        migrations.AlterField(
            model_name='products',
            name='effect',
            field=models.CharField(max_length=100, null=True, verbose_name='产品作用简介'),
        ),
        migrations.AlterField(
            model_name='products',
            name='is_solu',
            field=models.IntegerField(default=0, verbose_name='是否为解决方案,1:是解决方案,0:是产品'),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=100, verbose_name='产品名称'),
        ),
        migrations.AlterField(
            model_name='products',
            name='read_count',
            field=models.IntegerField(default=0, verbose_name='阅读量'),
        ),
        migrations.AlterField(
            model_name='products',
            name='src',
            field=models.ImageField(default='org/2019/08/ico.png', upload_to='org/%Y/%m', verbose_name='产品图片'),
        ),
        migrations.AlterField(
            model_name='products',
            name='type_num',
            field=models.IntegerField(default=0, verbose_name='产品分类号,0:车用尿素,1:加注设备'),
        ),
        migrations.AlterField(
            model_name='products',
            name='type_text',
            field=models.CharField(max_length=50, null=True, verbose_name='产品型号'),
        ),
    ]
