# Generated by Django 2.2.4 on 2019-08-21 03:33

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_auto_20190813_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRequire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobName', models.CharField(max_length=30, verbose_name='岗位名称')),
                ('workYears', models.IntegerField(default=0, verbose_name='工作经验')),
                ('needCount', models.IntegerField(default=1, verbose_name='招聘人数')),
                ('workPlace', models.CharField(default='桐乡', max_length=30, verbose_name='工作地点')),
                ('education', models.CharField(max_length=10, verbose_name='最低学历要求')),
                ('pushData', models.DateField(verbose_name='发布日期')),
                ('content', DjangoUeditor.models.UEditorField(default='岗位描述:       任职资格:', verbose_name='内容')),
            ],
        ),
        migrations.AlterField(
            model_name='products',
            name='effect',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='产品作用简介'),
        ),
        migrations.AlterField(
            model_name='products',
            name='type_text',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='产品型号'),
        ),
    ]
