# Generated by Django 2.2.4 on 2019-08-22 07:18

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20190821_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequire',
            name='content',
            field=DjangoUeditor.models.UEditorField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='jobrequire',
            name='workYears',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='工作经验'),
        ),
    ]
