# Generated by Django 2.2.4 on 2019-09-05 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20190822_1518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name_plural': '首页轮播图'},
        ),
        migrations.AlterModelOptions(
            name='jobrequire',
            options={'verbose_name_plural': '招聘信息'},
        ),
        migrations.AlterModelOptions(
            name='joinus',
            options={'verbose_name_plural': '加盟商'},
        ),
        migrations.AlterModelOptions(
            name='mynews',
            options={'ordering': ['date'], 'verbose_name_plural': '新闻'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['date'], 'verbose_name_plural': '产品'},
        ),
    ]
